### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by pkulium** [rainavyas/attack-comparative-assessment#1]
Quick question:
In the load_data.py file,  data_path = "/rds/project/rds-8YSp2LXTlkY/data/nlg_evaluation/topicalchat_usr/tc_usr_data.json"
where to get the json file?

**Comment by rainavyas** [comment]
Good spot! The data for TopicalChat can be downloaded from here: http://shikib.com/tc_usr_data.json

**Comment by pkulium** [comment]
got it, thanks!

**Comment by pkulium** [comment]
I have another brief question regarding the aggregation of results. 
Under the directory experiments/summeval/flant5-xl/, there are numerous folders. Could you kindly provide the scripts that were utilized to systematically collect the results?

**Comment by rainavyas** [comment]
I take it you have run eval.py? Depending on the specific arguments you pass, you will get results output in a directory such as:
`attack-comparative-assessment/experiments/summeval/flant5-xl/absolute/attack_eval/greedy-absolute-flant5xl/num_words-5`.
The .npy files contain the raw scores in this case for each system for each data point.

You can process these results (to get averages or the rank information as in the paper), by running process.py,  with the relevant arguments, e.g.
`python process.py --model_name flant5-xl --assessment comparative-consistency --data_name summeval --num_greedy_phrase_words 4 --attack_phrase greedy-comparative-cons-flant5xl --grid_latex_summ --avg_rank`

**Comment by rainavyas** [comment]
The ReadMe has been updated to include the command on how to process the results.
